AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Data Processing Pipeline'

Parameters:
  DBPassword:
    NoEcho: true
    Type: String
    Description: The database admin account password

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-data-bucket'
      VersioningConfiguration:
        Status: Enabled

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydatabase
      Engine: postgres
      MasterUsername: dbadmin
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      PubliclyAccessible: false

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}-cluster'

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AWS::StackName}-task'
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      TaskRoleArn: !Ref ECSTaskRole
      ContainerDefinitions:
        - Name: data-processor
          Image: '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/data-processor:latest'
          Environment:
            - Name: DB_HOST
              Value: !GetAtt DatabaseInstance.Endpoint.Address
            - Name: DB_NAME
              Value: mydatabase
            - Name: DB_USER
              Value: dbadmin
            - Name: DB_PASSWORD
              Value: !Ref DBPassword
            - Name: S3_BUCKET
              Value: !Ref DataBucket

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub '${DataBucket.Arn}/*'
        - PolicyName: RDSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-db:connect
                Resource: !Sub 'arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DatabaseInstance.DbiResourceId}/dbadmin'

Outputs:
  DataBucketName:
    Description: Name of the S3 bucket for data ingestion
    Value: !Ref DataBucket
  DatabaseEndpoint:
    Description: Endpoint of the RDS PostgreSQL instance
    Value: !GetAtt DatabaseInstance.Endpoint.Address
  ECSClusterName:
    Description: Name of the ECS cluster
    Value: !Ref ECSCluster